extends Node

var resource_path = "res://"



var building1 = load(resource_path + "buildings/building1.tres")
var building2 = load(resource_path + "buildings/building2.tres")
var building3 = load(resource_path + "buildings/building3.tres")
var building4 = load(resource_path + "buildings/building4.tres")
var building5 = load(resource_path + "buildings/building5.tres")
var building6 = load(resource_path + "buildings/building6.tres")
var building7 = load(resource_path + "buildings/building7.tres")
var building8 = load(resource_path + "buildings/building8.tres")
var building9 = load(resource_path + "buildings/building9.tres")
var building10 = load(resource_path + "buildings/building10.tres")
var building11 = load(resource_path + "buildings/building11.tres")
var building12 = load(resource_path + "buildings/building12.tres")
var building13 = load(resource_path + "buildings/building13.tres")
var building14 = load(resource_path + "buildings/building14.tres")
var building15 = load(resource_path + "buildings/building15.tres")
var building16 = load(resource_path + "buildings/building16.tres")
var building17 = load(resource_path + "buildings/building17.tres")
var building18 = load(resource_path + "buildings/building18.tres")
var building19 = load(resource_path + "buildings/building19.tres")
var building20 = load(resource_path + "buildings/building20.tres")
var building21 = load(resource_path + "buildings/building21.tres")
var building22 = load(resource_path + "buildings/building22.tres")
var building23 = load(resource_path + "buildings/building23.tres")
var building24 = load(resource_path + "buildings/building24.tres")
var building25 = load(resource_path + "buildings/building25.tres")
var building26 = load(resource_path + "buildings/building26.tres")
var building27 = load(resource_path + "buildings/building27.tres")
var building28 = load(resource_path + "buildings/building28.tres")



func loadResource():
	building1 = load(resource_path + "buildings/building1.tres")
	building2 = load(resource_path + "buildings/building2.tres")
	building3 = load(resource_path + "buildings/building3.tres")
	building4 = load(resource_path + "buildings/building4.tres")
	building5 = load(resource_path + "buildings/building5.tres")
	building6 = load(resource_path + "buildings/building6.tres")
	building7 = load(resource_path + "buildings/building7.tres")
	building8 = load(resource_path + "buildings/building8.tres")
	building9 = load(resource_path + "buildings/building9.tres")
	building10 = load(resource_path + "buildings/building10.tres")
	building11 = load(resource_path + "buildings/building11.tres")
	building12 = load(resource_path + "buildings/building12.tres")
	building13 = load(resource_path + "buildings/building13.tres")
	building14 = load(resource_path + "buildings/building14.tres")
	building15 = load(resource_path + "buildings/building15.tres")
	building16 = load(resource_path + "buildings/building16.tres")
	building17 = load(resource_path + "buildings/building17.tres")
	building18 = load(resource_path + "buildings/building18.tres")
	building19 = load(resource_path + "buildings/building19.tres")
	building20 = load(resource_path + "buildings/building20.tres")
	building21 = load(resource_path + "buildings/building21.tres")
	building22 = load(resource_path + "buildings/building22.tres")
	building23 = load(resource_path + "buildings/building23.tres")
	building24 = load(resource_path + "buildings/building24.tres")
	building25 = load(resource_path + "buildings/building25.tres")
	building26 = load(resource_path + "buildings/building26.tres")
	building27 = load(resource_path + "buildings/building27.tres")
	building28 = load(resource_path + "buildings/building28.tres")
